language: php

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

sudo: false

before_script:
  - phpenv config-rm xdebug.ini
  - composer update $COMPOSER_FLAGS
  - composer validate

script: vendor/bin/phpunit
