language: php

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
  - phpenv config-rm xdebug.ini
  - COMPOSER_MEMORY_LIMIT=-1 composer update $COMPOSER_FLAGS

script: vendor/bin/phpunit
