language: php

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4
    - php: 8.0

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak
      COMPOSER_MEMORY_LIMIT=-1

before_script:
  - phpenv config-rm xdebug.ini
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyze -c phpstan.neon
  - vendor/bin/phpunit
